{application,ehttp_session,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[ehhtp_session_config,ehttp_session,ehttp_session_app,
                        ehttp_session_backend,ehttp_session_config,
                        ehttp_session_generator]}]}.
